///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) Crossbar.io Technologies GmbH and contributors
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
///////////////////////////////////////////////////////////////////////////////

#include "Settings.h"

#include <cstdlib>
#include <boost/asio/ip/address.hpp>
#include <boost/program_options.hpp>
#include <iostream>

namespace {
const std::string ROUTER_IP_ADDRESS_STRING("127.0.0.1");
const boost::asio::ip::address ROUTER_IP_ADDRESS(
        boost::asio::ip::address::from_string(ROUTER_IP_ADDRESS_STRING));
const std::string DEFAULT_REALM("opplive");
const uint16_t DEFAULT_RAWSOCKET_PORT(9000);
const std::string DEFAULT_UDS_PATH("/tmp/crossbar.sock");
}

Settings::Settings() :
        m_debug(false), m_realm(DEFAULT_REALM), m_rawsocket_endpoint(
                ROUTER_IP_ADDRESS, DEFAULT_RAWSOCKET_PORT)
#ifdef BOOST_ASIO_HAS_LOCAL_SOCKETS
                , m_uds_endpoint(DEFAULT_UDS_PATH)
#endif
{
}

bool Settings::debug() const {
    return m_debug;
}

const std::string& Settings::realm() const {
    return m_realm;
}

const boost::asio::ip::tcp::endpoint& Settings::rawsocket_endpoint() const {
    return m_rawsocket_endpoint;
}

#ifdef BOOST_ASIO_HAS_LOCAL_SOCKETS
const boost::asio::local::stream_protocol::endpoint& Settings::uds_endpoint() const {
    return m_uds_endpoint;
}
#endif

void Settings::set_debug(bool value) {
    m_debug = value;
}

void Settings::set_realm(const std::string& realm) {
    m_realm = realm;
}

void Settings::set_rawsocket_endpoint(const std::string& ip_address,
        uint16_t port) {
    m_rawsocket_endpoint = boost::asio::ip::tcp::endpoint(
            boost::asio::ip::address::from_string(ip_address), port);
}

#ifdef BOOST_ASIO_HAS_LOCAL_SOCKETS
void Settings::set_uds_endpoint(const std::string& path) {
    m_uds_endpoint = boost::asio::local::stream_protocol::endpoint(path);
}
#endif 
